### ISSUE TITLE
Nome comandi python

### ISSUE THREAD

**Issue by yakky** [simobasso/djangogirls_revamped#16]
### Descrizione

Bisogna chiarire di più (all'inizio e almeno nei primi passaggi), che i comandi `python` / `pip` potrebbe essere necessario scriverli come `python3` / `pip3` (questo è soprattutto un appunto per noi coach)

La cosa ideale sarebbe riuscire ad avere una casistica che ci permetta fin dall'inizio di sapere qual è la situazione della partecipante.

Fosse anche solo un griglia per il coach che si segna le cose in fase di installazione

Può anche valere la pena ripetere spesso l'avviso messo nella pagina di installazione.

Forse sostituire tutti i comandi `python`, `pip` con i rispettivi `3` potrebbe essere utile: dovrebbe essere più compatibile e soprattuto è un segnale utile anche ai coach per sapere di dover eventualmente far provare l'altra variante

### PATH del file

* installation/README.md (e altrove)

**Comment by brunato** [comment]
Il problema non è tanto per i coach ma per le allieve che comunque poi ad ogni comando rischiano di confondersi e ripetere gli stessi errori. Forse, almeno per le parti Linux/Mac, varrebbe la pena mettere python3/pip3 sempre, dato che al momento vale in generale con il metodo di installazione adottato (quindi lavorando in user space senza virtualenvs).

Quindi a mio parere, per quello che vale, ok avviso/i ma anche sostituzione ove possibile di python3/pip3 al posto di python/pip.

**Comment by yakky** [comment]
@brunato ho corretto in #23 come suggerivi tu e aggiungendo comunque una nota iniziale
