### ISSUE TITLE
installazione python via homebrew?

### ISSUE THREAD

**Issue by scontini76** [simobasso/djangogirls_revamped#27]
Sotto macOS trovo molto pratico usare [brew](http://brew.sh) per installare le applicazioni, compreso l'interprete python. Pensate sia il caso di proporlo nel tutorial come metodo alternativo di installazione di python? Magari è già usato da qualche partecipante dal workshop e magari in futuro può rilevarsi utile alle partecipanti anche in un secondo momento. Cosa ne dite?

**Comment by yakky** [comment]
PR welcome! :D 
Scherzi a parte mi sembra una buona idea per chi già lo usasse.
Riusciresti a proporre una pull request? Non ho mac quindi avrei qualche difficoltà a tirare giù la procedura

**Comment by scontini76** [comment]
certo, provo a buttare giù io a qualcosa nei prossimi due giorni!

**Comment by yakky** [comment]
tks!

**Comment by yakky** [comment]
Fixed in #32
