### ISSUE TITLE
Usare path per Django invece di url

### ISSUE THREAD

**Issue by valentinogagliardi** [simobasso/djangogirls_revamped#28]
### Descrizione

L'attuale versione del tutorial usa ancora il "vecchio stile" per dichiarare gli url: 

```python
url(r'^admin/', admin.site.urls),`
```

Il nuovo formato prevede l'uso di path:

```python
path('admin/', admin.site.urls),
```

Sarebbe opportuno aggiornare tutto, a partire dal [template del progetto](https://github.com/DjangoGirlsItalia/startproject)

Se interessa posso preparare un PR per entrambi.

### PATH del file

djangogirls-tutorial/master/django_urls/README.md

**Comment by yakky** [comment]
Fixed in #29
