### ISSUE TITLE
installazione django per windows8/10

### ISSUE THREAD

**Issue by nuvoletta8** [simobasso/djangogirls_revamped#34]
### Descrizione

esplodendo il sottoparagrafo c'è il riferimento alla vecchia versione

python -m pip install django~=1.11.0 whitenoise~=3.3.0
anzichè django~=2.1 whitenoise~=4.1.0

### PATH del file

https://djangogirls-italia.netlify.com/installation/#windows-8-e-windows-10

### Versione di Django

modificare da django~=1.11.0 whitenoise~=3.3.0 a  django~=2.1 whitenoise~=4.1.0

### Sistema Operativo

windows 8 - windows 10

**Comment by yakky** [comment]
Fixed by #37
