### ISSUE TITLE
aggiornare creazione progetto windows - riferimento a tutorial vecchio!!!

### ISSUE THREAD

**Issue by nuvoletta8** [simobasso/djangogirls_revamped#35]
### Descrizione
Creare un Progetto: Windows

il comando punta al vecchio tuttorial , 

python -m django startproject --template=https://github.com/simobasso/startproject/archive/master.zip --name=Procfile mysite .

anzichè =https://github.com/DjangoGirlsItalia/startproject/archive/master.zip 

### PATH del file

https://djangogirls-italia.netlify.com/django_start_project/#creare-un-progetto-windows

### Versione di Python

3.7 

### Sistema Operativo

windows

**Comment by yakky** [comment]
fixed by #36
