### ISSUE TITLE
OperationalError Exception Value: 	  no such table: blog_post

### ISSUE THREAD

**Issue by nuvoletta8** [simobasso/djangogirls_revamped#39]
### Descrizione

Amministrazione Django, dopo aver abilitato l'amministrazione con modifiche al file admin.py e creato il superuser per l'amministrazione, viene chiesto di loggarsi ed inserire qualche post di prova.
In caso di questo tipo di errore
![errore_db](https://user-images.githubusercontent.com/32671124/54448210-74d8df00-474b-11e9-928d-2372073d17a2.JPG)

basta stoppare il webserver (CTRL +C) ridare il migrate del db

>python manage.py migrate 

e startare nuovamente il webserver

### PATH del file

https://djangogirls-italia.netlify.com/django_admin/#django-admin

### Sistema Operativo

Windows 10

**Comment by yakky** [comment]
come d'accordo su slack vediamo se domani si ripresenta e nel caso proviamo a capire che succede

**Comment by yakky** [comment]
Non più riscontrato in the wild
:man_shrugging:
