### ISSUE TITLE
Django tutorial: aggiornare riferimenti alla documentazione

### ISSUE THREAD

**Issue by scontini76** [simobasso/djangogirls_revamped#40]
### Descrizione

Ci sono riferimenti alla documentazione di Django 1.11 o precedenti quando il tutorial è stato portato alla 2.1

### PATH del file

whats_next/README.md
django_forms/README.md
django_urls/README.md
django_views/README.md

se va bene ci penso io appena sono meno assonnato!

**Comment by yakky** [comment]
Fixed in  #41
