### ISSUE TITLE
Typo su django_start_project/README.md

### ISSUE THREAD

**Issue by valentinogagliardi** [simobasso/djangogirls_revamped#43]
### Descrizione

Errore di traduzione: (su Windows, è probabile che tu **deva** premere Ctrl+Break)

debba invece di "deva"

### PATH del file

/django_start_project/README.md

**Comment by valentinogagliardi** [comment]
Assegnami pure, posso fixare io

**Comment by yakky** [comment]
:bowing_man:

**Comment by xrmx** [comment]
Sistemato si può chiudere :)

**Comment by yakky** [comment]
:dart:
